version: '3.8'

services:
  app:
    build:
      context: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgresql
      - mongodb
    environment:
      ENV_emit: docker
      PG_HOST: postgresql
      PG_PORT: 5432
      PG_DB: act3database
      PG_USER: user
      PG_PASS: password
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: emitdatabase
    command: php utils/dbResetPostgresql.util.php

  postgresql:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_DB: act3database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
